"use client";

import { ChangeEvent, useRef, useState } from "react";
import type { ApplicationDetails } from "./application-details";
import { createXlsx, readXlsx } from "../lib/xlsx-transfer";

type Props = { applicationsCount:number; onImported:(applications:ApplicationDetails[])=>void; onClear:()=>void };
type ExportFormat = "json" | "csv" | "xlsx" | "pdf";
type ImportFormat = "json" | "csv" | "xlsx";
type HistoryRecord = Record<string, unknown>;
type BackupApplication = ApplicationDetails & { history?: HistoryRecord[] };
type Backup = { version:number; applications:BackupApplication[] };
const columns = ["company","role","location","status","appliedDate","salary","url","notes","contactEmail","source","nextStep","nextActionDate"];

function localDate() { const now=new Date(); return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`; }
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
function parseCsv(text:string) { const rows:string[][]=[]; let row:string[]=[], cell="", quoted=false; for(let i=0;i<text.length;i++){ const char=text[i], next=text[i+1]; if(char==='"'&&quoted&&next==='"'){cell+='"';i++;} else if(char==='"'){quoted=!quoted;} else if(char===','&&!quoted){row.push(cell);cell="";} else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell="";} else cell+=char; } row.push(cell);if(row.some(Boolean))rows.push(row);return rows; }
const escapeHtml=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]??char));

function FormatPicker<T extends string>({label,value,onChange,items}:{label:string;value:T;onChange:(value:T)=>void;items:{value:T;title:string;subtitle:string}[]}) { return <div className="format-picker" aria-label={label}>{items.map(item=><button key={item.value} className={value===item.value?"active":""} onClick={()=>onChange(item.value)} type="button"><strong>{item.title}</strong><span>{item.subtitle}</span></button>)}</div>; }

export default function DataTransferPanel({applicationsCount,onImported,onClear}:Props){
 const inputRef=useRef<HTMLInputElement>(null); const [busy,setBusy]=useState<"export"|"import"|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [exportFormat,setExportFormat]=useState<ExportFormat>("json"); const [importFormat,setImportFormat]=useState<ImportFormat>("json");
 const exportItems:{value:ExportFormat;title:string;subtitle:string}[]=[{value:"json",title:"JSON",subtitle:"Full backup"},{value:"csv",title:"CSV",subtitle:"Simple table"},{value:"xlsx",title:"Excel",subtitle:"Two worksheets"},{value:"pdf",title:"PDF",subtitle:"Printable report"}];
 const importItems:{value:ImportFormat;title:string;subtitle:string}[]=[{value:"json",title:"JSON",subtitle:"Full backup"},{value:"csv",title:"CSV",subtitle:"Application rows"},{value:"xlsx",title:"Excel",subtitle:"Workbook"}];
 async function exportData(){setBusy("export");setError("");setMessage("");try{const response=await fetch("/api/applications/backup");if(!response.ok)throw new Error("Export could not be created.");const backup=await response.json() as Backup;if(!Array.isArray(backup.applications))throw new Error("Export data is invalid.");const filename=`applyly-${localDate()}`;
  if(exportFormat==="xlsx"){const applications=backup.applications.map(application=>Object.fromEntries(Object.entries(application).filter(([key])=>key!=="history")));const history=backup.applications.flatMap(application=>(application.history??[]).map(entry=>({applicationId:application.id,...entry})));const blob=new Blob([createXlsx(applications,history)],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${filename}.xlsx`;link.click();URL.revokeObjectURL(url);setMessage("Your Excel workbook was downloaded.");return;}
  if(exportFormat==="pdf"){const popup=window.open("","_blank");if(!popup)throw new Error("Allow pop-ups to open the PDF report.");popup.opener=null;const rows=backup.applications.map(app=>`<tr><td>${escapeHtml(app.company)}</td><td>${escapeHtml(app.role)}</td><td>${escapeHtml(app.status)}</td><td>${escapeHtml(app.appliedDate)}</td><td>${escapeHtml(app.location)}</td></tr>`).join("");popup.document.write(`<!doctype html><html><head><title>Applyly report</title><style>body{font:13px Arial,sans-serif;color:#202321;margin:32px}h1{font-size:24px}p{color:#687069}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{text-align:left;padding:9px;border-bottom:1px solid #ddd}th{background:#f3f5f1}@media print{body{margin:16mm}}</style></head><body><h1>Applyly application report</h1><p>${backup.applications.length} applications exported ${escapeHtml(new Date().toLocaleString())}</p><table><thead><tr><th>Company</th><th>Role</th><th>Status</th><th>Applied</th><th>Location</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);popup.document.close();setMessage("The PDF report opened. Choose Save as PDF in the print dialog.");return;}
  const content=exportFormat==="json"?JSON.stringify(backup,null,2):[columns.join(","),...backup.applications.map(app=>columns.map(column=>csvCell(app[column])).join(","))].join("\n");const blob=new Blob([content],{type:exportFormat==="json"?"application/json":"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${filename}.${exportFormat}`;link.click();URL.revokeObjectURL(url);setMessage(`Your ${exportFormat.toUpperCase()} export was downloaded.`);
 }catch(reason){setError(reason instanceof Error?reason.message:"Export could not be created.");}finally{setBusy(null);}}
 async function importData(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setError("");setMessage("");try{if(file.size>10*1024*1024)throw new Error("Choose a file smaller than 10 MB.");let backup:unknown;if(importFormat==="json")backup=JSON.parse(await file.text());else if(importFormat==="csv"){const [headers,...rows]=parseCsv(await file.text());backup={version:1,applications:rows.map((row,index)=>({id:index+1,...Object.fromEntries(headers.map((header,column)=>[header,row[column]??""]))}))};}else{const workbook=readXlsx(await file.arrayBuffer());backup={version:1,applications:workbook.applications.map((app,index)=>{const id=Number(app.id)||index+1;return {...app,id,history:workbook.history.filter(entry=>Number(entry.applicationId)===id).map(entry=>Object.fromEntries(Object.entries(entry).filter(([key])=>key!=="applicationId")))};})};}
  if(!backup||typeof backup!=="object"||!("version" in backup)||backup.version!==1||!("applications" in backup)||!Array.isArray(backup.applications))throw new Error("Choose a valid Applyly file.");if(!window.confirm("Replace all current applications and status history with this import? Your browser preferences stay unchanged."))return;setBusy("import");const response=await fetch("/api/applications/backup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(backup)});const data=await response.json();if(!response.ok)throw new Error(data.error??"Import failed.");onImported(data.applications??[]);setMessage(`Imported ${data.applications?.length??0} application${data.applications?.length===1?"":"s"}.`);
 }catch(reason){setError(reason instanceof Error?reason.message:"Import failed.");}finally{setBusy(null);}}
 const accept=importFormat==="json"?"application/json,.json":importFormat==="csv"?"text/csv,.csv":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,.xlsx";
 return <section className="data-layout"><section className="card data-card"><div className="card-head"><div><h2>Export your data</h2><p className="sub">Choose the format that fits your next step.</p></div></div><div className="data-body"><p>JSON is the safest complete backup. Excel keeps applications and status history on separate worksheets. PDF creates a readable report.</p><FormatPicker label="Export format" value={exportFormat} onChange={setExportFormat} items={exportItems}/><button className="primary" onClick={exportData} disabled={busy!==null}>{busy==="export"?"Preparing export...":exportFormat==="pdf"?"Open PDF report":`Export ${exportFormat.toUpperCase()}`}</button></div></section><section className="card data-card"><div className="card-head"><div><h2>Import your data</h2><p className="sub">Restore a supported structured data file.</p></div></div><div className="data-body"><p>Import replaces current applications. JSON and Excel can restore history; CSV imports application rows.</p><FormatPicker label="Import format" value={importFormat} onChange={setImportFormat} items={importItems}/><input ref={inputRef} className="file-input" type="file" accept={accept} onChange={importData}/><button className="secondary-button" onClick={()=>inputRef.current?.click()} disabled={busy!==null}>{busy==="import"?"Importing...":`Choose ${importFormat.toUpperCase()} file`}</button></div></section><section className="card data-card danger-card"><div className="card-head"><div><h2>Delete all data</h2><p className="sub">Remove every local application and status timeline.</p></div></div><div className="data-body"><p>You have <strong>{applicationsCount}</strong> saved application{applicationsCount===1?"":"s"}. This cannot be undone unless you export a backup first.</p><button className="danger-button" onClick={onClear} disabled={!applicationsCount||busy!==null}>Delete all applications</button></div></section>{(message||error)&&<div className={`notice ${error?"error":"success"}`}>{error||message}<button onClick={()=>{setMessage("");setError("");}} aria-label="Dismiss">Dismiss</button></div>}</section>;
}